### ISSUE TITLE
Can you share the elevan labs and other voice-cloning data to replicate the results?

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [audio-df-ucb/ClonedVoiceDetection#1]
Hello

I would like to replicate results in paper for that, Can you share the elevan labs and other voice-cloning data to replicate the results?

**Comment by gthmk** [comment]
Hi. The data is really large and has been archived on a local disk so we can't easily share it with you. You can use the sample code we provide [here](https://github.com/audio-df-ucb/ClonedVoiceDetection/blob/main/src/packages/ElevenLabsDeepFakeGenerator.py) to generate your own eleven labs data.
